### ISSUE TITLE
SE Protection added even if not selected for product

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/whmcs-addon#13]
### Version information
WHMCS Version

7.4.2-release.1

PHP Version

5.6.36

Curl Version

7.60.0

Addon Version

1

SpamExperts Version

134224

Diagnostic

WHMCS Version

OK

PHP Version

OK

SpamExperts API Connection

OK

SpamExperts Module

OK

SpamExperts Reseller Module

OK

### Steps to replicate

 1. Client adds an order in WHMCS without SE

### Actual result

The domain is protected

### Expected result

The domain shouldn't be protected

### Other notes
![image002](https://user-images.githubusercontent.com/25361420/40903197-4379ed92-67df-11e8-880f-e06d56e043c6.png)
![image003](https://user-images.githubusercontent.com/25361420/40903198-43987604-67df-11e8-906c-73210372b0df.png)

WHMCS: https://my.spamexperts.com/admin/supporttickets.php?action=view&id=214115

**Comment by claudiapetre** [comment]
Please, ask from the client a screenshot from Client Profile-> Summary tab-> Products/Services section (is located above Addon section)

If the product SpamExperts Inbox Protection is displayed, then protection is correctly added, since the client has a kwspamexperts product enabled. The addon is not directly added to a client, is used to configure a product/service.

**Comment by narciswork** [comment]
File attached

![image002](https://user-images.githubusercontent.com/26410046/41905192-1d656012-7943-11e8-9ec2-cd11424e6349.jpg)

Informed client to check automatic settings as well.

**Comment by narciswork** [comment]
![products](https://user-images.githubusercontent.com/26410046/41905582-4f92dc1c-7944-11e8-8601-e7ff20f73a2d.png)

Attached screenshot redacted

**Comment by claudiapetre** [comment]
We couldn't replicate this issue. The requested information was not received.
